Load scene by default for mj models and allow variants
robot-descriptions/robot_descriptions.py pull request #76
Opened 2024-04-22 09:30 UTC by fabinsch

Hi @stephane-caron ,

thanks for this nice library to load a bunch of robot models with different frameworks. Lately I was trying some mujoco models and I had a quick fix locally to load the `scene.xml` (which was more useful in my case).

I saw #74 and also #62 and thought that a minimal adaptation allowing for both could be the change proposed in this PR.
This adds a `variant` keyword, that I set the `scene` by default. If a robot has no `scene.xml`, it will still just load the pure robot model as define in each specific file per robot. With this solution, we do not have to modify every single file but I am very open to changes and happy to integrate your remarks.

2024-04-22 12:33 UTC, stephane-caron requested changes
Thank you for this feature that can be immediately useful to MuJoCo users :+1: I suggest we roll it in a backward-compatible manner with v1.10+, then have a more advanced variant mechanism for v2.

2024-04-22 12:33 UTC, stephane-caron commented on robot_descriptions/loaders/mujoco.py
> +    variant: Optional[str] = "scene",
```suggestion
    variant: Optional[str] = None,
```

I suggest we keep the API backward compatible and only do a minor version bump for the next release. Users can load scenes using this feature at present, and we can address the full feature https://github.com/robot-descriptions/robot_descriptions.py/issues/62 for the next major version.

2024-04-22 17:07 UTC, kevinzakka commented
Just chiming in that I disagree that scene should be the default.

2024-04-23 11:57 UTC, stephane-caron commented
> Just chiming in that I disagree that scene should be the default.

Yes, this was the original proposal but we have changed it in https://github.com/robot-descriptions/robot_descriptions.py/pull/76/commits/f6096953e3f3aef3bf3124f2133656b063c9a9cb. Now the PR is backward compatible and one should pass `variant="scene"` explicitly to load the scene.

2024-04-23 14:39 UTC, stephane-caron approved these changes

2024-04-24 09:51 UTC, merged

2024-04-24 09:51 UTC, stephane-caron commented
Thank you for this contribution @fabinsch 😃

2024-04-25 22:06 UTC, kevinzakka commented
Thank you @fabinsch and @stephane-caron!